# Generated by Django 2.0.2 on 2018-03-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tasks',
            field=models.ManyToManyField(through='assignments.Assignment', to='assignments.Task'),
        ),
    ]
