# Generated by Django 2.0.2 on 2018-03-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='assignments',
            field=models.ManyToManyField(related_name='Groups', to='assignments.Assignment'),
        ),
    ]
