# Generated by Django 2.0.2 on 2018-03-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('students', '0002_auto_20180316_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignments', models.ManyToManyField(to='assignments.Assignment')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='assignments',
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(to='students.Group'),
        ),
    ]
